name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  WEARMMR_KEY_ALIAS: ${{secrets.WEARMMR_KEY_ALIAS}}
  WEARMMR_KEY_PASSWORD: ${{secrets.WEARMMR_KEY_PASSWORD}}
  WEARMMR_KEYSTORE_FILE: ${{secrets.WEARMMR_KEYSTORE_FILE}}
  WEARMMR_KEYSTORE_PASSWORD: ${{secrets.WEARMMR_KEYSTORE_PASSWORD}}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup G services
      run: cp app/google-services.json.example app/google-services.json
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        validate-wrappers: true
    - name: Detekt
      run: ./gradlew detekt
    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: detekt
        path: |
          app/build/reports/detekt/detekt.html
          data/build/reports/detekt/detekt.html
          domain/build/reports/detekt/detekt.html
  ui-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.2.2
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup G services
        run: cp app/google-services.json.example app/google-services.json
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          validate-wrappers: true
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-34
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          script: ./gradlew connectedDebugAndroidTest
          arch: x86_64
          target: google_apis
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          api-level: 34
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup G services
      run: cp app/google-services.json.example app/google-services.json
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        validate-wrappers: true
    - name: Run tests
      run: ./gradlew testDebugUnitTest
