name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  WEARMMR_KEY_ALIAS: ${{secrets.WEARMMR_KEY_ALIAS}}
  WEARMMR_KEY_PASSWORD: ${{secrets.WEARMMR_KEY_PASSWORD}}
  WEARMMR_KEYSTORE_FILE: ${{secrets.WEARMMR_KEYSTORE_FILE}}
  WEARMMR_KEYSTORE_PASSWORD: ${{secrets.WEARMMR_KEYSTORE_PASSWORD}}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup G services
      run: cp app/google-services.json.example app/google-services.json
    - uses: gradle/wrapper-validation-action@v1
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Gradle
      run: ./gradlew detekt lintDebug --continue
  ui-tests:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup G services
        run: cp app/google-services.json.example app/google-services.json
      - uses: gradle/wrapper-validation-action@v1
      - name: Accept licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      - name: Run tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew connectedDebugAndroidTest
          api: 29
          tag: default
          abi: x86
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup G services
      run: cp app/google-services.json.example app/google-services.json
    - uses: gradle/wrapper-validation-action@v1
    - name: Run tests
      run: ./gradlew testDebugUnitTest
