name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  WEARMMR_KEY_ALIAS: ${{secrets.WEARMMR_KEY_ALIAS}}
  WEARMMR_KEY_PASSWORD: ${{secrets.WEARMMR_KEY_PASSWORD}}
  WEARMMR_KEYSTORE_FILE: ${{secrets.WEARMMR_KEYSTORE_FILE}}
  WEARMMR_KEYSTORE_PASSWORD: ${{secrets.WEARMMR_KEYSTORE_PASSWORD}}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup G services
      run: cp app/google-services.json.example app/google-services.json
    - name: Check Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Detekt
      uses: gradle/gradle-build-action@v2.8.0
      with:
        arguments: detekt
    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: detekt
        path: |
          app/build/reports/detekt/detekt.html
          data/build/reports/detekt/detekt.html
          domain/build/reports/detekt/detekt.html
  ui-tests:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3.5.3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup G services
        run: cp app/google-services.json.example app/google-services.json
      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2.8.0
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          script: ./gradlew connectedDebugAndroidTest
          api-level: 29
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup G services
      run: cp app/google-services.json.example app/google-services.json
    - name: Check Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Install latest build tools
      run: echo "y" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0-rc3"
    - name: Run tests
      uses: gradle/gradle-build-action@v2.8.0
      with:
        arguments: testDebugUnitTest
